import { useState } from 'react';
import { ArrowUpRight, CalendarDays, Car, Check, ChevronDown, ChevronLeft, ChevronRight, Mail, MapPin, Menu, MessageCircle, Phone, ShieldCheck, Sparkles, Users, X, Zap } from 'lucide-react';

const spaces = [
 {name:'The Grand Hall',cap:'1,000 guests',copy:'A dramatic flagship setting imagined for spectacular receptions, galas and large-scale celebrations.',img:'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=1400&q=85'},
 {name:'The Royale Room',cap:'500 guests',copy:'A refined, flexible room concept for weddings, corporate gatherings and elegant social occasions.',img:'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=85'},
 {name:'The Intimate Suite',cap:'150 guests',copy:'An intimate environment for private celebrations, dinners, launches and smaller gatherings.',img:'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1400&q=85'}
];
const eventTypes = [
 ['Weddings','From intimate ceremonies to spectacular receptions, create a celebration your guests will remember.','https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1000&q=80'],
 ['Corporate Events','Polished spaces for meetings, launches, dinners and company celebrations.','https://images.unsplash.com/photo-1505373877841-8d25f7d46678?auto=format&fit=crop&w=1000&q=80'],
 ['Birthdays & Celebrations','Bring birthdays, milestones and joyful gatherings to life in style.','https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1000&q=80'],
 ['Private Parties','A sophisticated backdrop for the occasions you want to make personal.','https://images.unsplash.com/photo-1530103862676-de8c9debad1d?auto=format&fit=crop&w=1000&q=80'],
 ['Conferences','A professional setting designed around focused sessions and memorable hospitality.','https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1000&q=80'],
 ['Graduations','A polished stage for proud moments, family photographs and new beginnings.','https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=1000&q=80']
];
const gallery = [
 ['Weddings','https://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop&w=1200&q=85'],['Corporate','https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1200&q=85'],['Celebrations','https://images.unsplash.com/photo-1531058020387-3be344556be6?auto=format&fit=crop&w=1200&q=85'],['Venue','https://images.unsplash.com/photo-1507504031003-b417219a0fde?auto=format&fit=crop&w=1200&q=85'],['Weddings','https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?auto=format&fit=crop&w=1200&q=85'],['Corporate','https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=85'],['Celebrations','https://images.unsplash.com/photo-1505236858219-8359eb29e329?auto=format&fit=crop&w=1200&q=85'],['Venue','https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=1200&q=85']
];
const packages = [
 ['Essential','₦750,000','Intimate celebrations','Event space','Seating setup','Tables & chairs','Basic lighting','Security','Parking','Venue support'],
 ['Signature','₦1,500,000','Larger celebrations & weddings','Event space','Enhanced seating setup','Tables & chairs','Basic lighting','Security','Parking','Venue support'],
 ['Grand','₦2,500,000','Premium full-scale experience','Event space','Premium seating setup','Tables & chairs','Enhanced lighting','Security','Parking','Venue support']
];
const faqs = ['How many guests can the venue accommodate?','What types of events do you host?','Can I schedule a venue tour?','Is parking available?','Do you provide tables and chairs?','Can I use my own decorator?','Do you have backup power?','How far in advance should I book?','How much does venue hire cost?','Can I request a custom package?'];
const testimonials = [
 ['Amara O.','Everything felt beautifully organised from the moment we arrived. The space looked incredible and our guests loved it.'],
 ['Daniel K.','The atmosphere, layout and presentation made it easy to imagine our event here. A beautifully considered concept.'],
 ['Tomi A.','The experience feels premium from the first click. The spaces and packages are presented so clearly.']
];

function App(){
 const [menu,setMenu]=useState(false),[filter,setFilter]=useState('ALL'),[light,setLight]=useState<number|null>(null),[faq,setFaq]=useState<number|null>(null),[slide,setSlide]=useState(0),[sent,setSent]=useState(false);
 const go=(id:string)=>{document.getElementById(id)?.scrollIntoView({behavior:'smooth'});setMenu(false)};
 const whatsapp=()=>alert('Demo WhatsApp CTA — no real message was sent. A client version would connect this button to the venue\'s verified WhatsApp number.');
 const submit=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();if(e.currentTarget.checkValidity())setSent(true)};
 return <div className="site">
  <div className="demo-bar">SALES DEMO · FICTIONAL VENUE CONCEPT · NOT AN OFFICIAL BUSINESS WEBSITE</div>
  <header><button className="brand" onClick={()=>go('home')}><strong>GRAND LUXE</strong><span>EVENTS</span></button><nav>{['Home','The Venue','Spaces','Gallery','Packages','FAQs','Contact'].map((x,i)=><button key={x} onClick={()=>go(['home','venue','spaces','gallery','packages','faqs','contact'][i])}>{x}</button>)}<button className="nav-cta" onClick={()=>go('booking')}>BOOK A TOUR <ArrowUpRight size={15}/></button></nav><button className="hamb" aria-label="Open menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
  {menu&&<div className="mobile-menu">{['Home','The Venue','Spaces','Gallery','Packages','FAQs','Contact'].map((x,i)=><button key={x} onClick={()=>go(['home','venue','spaces','gallery','packages','faqs','contact'][i])}>{x}</button>)}<button className="nav-cta" onClick={()=>go('booking')}>BOOK A TOUR</button></div>}
  <main>
   <section id="home" className="hero"><div className="hero-bg"/><div className="hero-content"><span className="eyebrow"><Sparkles size={13}/> WEBSITE CONCEPT · DEMO</span><p className="kicker">LAGOS · VENUES · GRAND OCCASIONS</p><h1>Where Unforgettable Moments Become <em>Grand Celebrations</em></h1><p className="hero-text">A sophisticated event destination designed for weddings, celebrations, corporate gatherings and unforgettable occasions.</p><div className="hero-actions"><button onClick={()=>go('booking')}>BOOK A VENUE TOUR <ArrowUpRight size={17}/></button><button className="outline" onClick={whatsapp}><MessageCircle size={17}/> CHAT ON WHATSAPP</button></div><div className="trust">Weddings <b>•</b> Corporate Events <b>•</b> Celebrations <b>•</b> Private Events</div></div><div className="hero-side"><span>FICTIONAL CONCEPT</span><small>Illustrative content only</small></div></section>
   <section id="venue" className="intro section"><div className="section-label">01 / THE GRAND LUXE EXPERIENCE</div><div className="intro-grid"><div><p className="kicker">DESIGNED FOR MOMENTS THAT DESERVE MORE.</p><h2>Let the venue set the <em>tone.</em></h2><p>From intimate celebrations to grand occasions, Grand Luxe Events is a fictional venue concept built around elegant settings, thoughtful amenities and a seamless guest experience.</p><button className="text-btn" onClick={()=>go('spaces')}>EXPLORE THE VENUE <ArrowUpRight size={16}/></button></div><div className="feature-img"><img src="https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=1400&q=85" alt="Generic luxury event venue demo"/><span>DEMO VENUE IMAGE</span></div></div></section>
   <section className="stats"><div><Users/><strong>1,000+</strong><span>Guest Capacity</span></div><div><Car/><strong>500+</strong><span>Parking Spaces</span></div><div><Sparkles/><strong>3</strong><span>Flexible Event Spaces</span></div><div><Zap/><strong>24/7</strong><span>Power & Security</span></div><p>Demo specifications — replace with the client's actual venue information.</p></section>
   <section id="events" className="section event-section"><div className="section-label">02 / OCCASIONS</div><p className="kicker">MADE FOR EVERY GRAND OCCASION</p><h2>Whatever you're celebrating,<br/><em>make it count.</em></h2><div className="event-grid">{eventTypes.map(([name,copy,img])=><article key={name}><img src={img} alt="Generic event demo" loading="lazy"/><div><span>DEMO EVENT TYPE</span><h3>{name}</h3><p>{copy}</p><button onClick={()=>go('booking')}>PLAN YOUR EVENT <ArrowUpRight size={15}/></button></div></article>)}</div></section>
   <section id="spaces" className="section spaces"><div className="section-head"><div><p className="kicker">03 / OUR SPACES</p><h2>Room to create <em>something extraordinary.</em></h2></div><span className="section-label">FICTIONAL SPACES · DEMO</span></div><div className="space-grid">{spaces.map((s,i)=><article key={s.name}><div className="space-img"><img src={s.img} alt="Generic venue space demo" loading="lazy"/><span>0{i+1}</span></div><div className="space-copy"><div><span>DEMO SPACE</span><h3>{s.name}</h3></div><b>{s.cap}</b><p>{s.copy}</p><button onClick={()=>alert('Demo interaction — this space detail would become a real venue page after customization.')}>VIEW SPACE <ArrowUpRight size={15}/></button></div></article>)}</div></section>
   <section className="facilities section"><div className="section-head"><div><p className="kicker">WHY GRAND LUXE</p><h2>Every detail, <em>considered.</em></h2></div><span className="section-label">04 / FACILITIES</span></div><div className="facility-grid">{[[Sparkles,'Premium Interiors','Beautifully designed spaces that create the right atmosphere for every occasion.'],[Zap,'Reliable Power','Designed to keep your celebration running smoothly.'],[Car,'Ample Parking','Convenient parking arrangements for you and your guests.'],[Users,'Professional Support','A dedicated team focused on helping your event run seamlessly.'],[CalendarDays,'Flexible Event Spaces','Spaces adaptable to different event sizes and formats.'],[ShieldCheck,'Security','A comfortable and secure environment for your guests.']].map(([Icon,title,copy])=>{const I=Icon as typeof Sparkles;return <article key={title}><I/><span>DEMO FEATURE</span><h3>{title as string}</h3><p>{copy as string}</p></article>})}</div></section>
   <section id="gallery" className="section gallery"><div className="section-head"><div><p className="kicker">05 / THE GALLERY</p><h2>See the <em>possibility.</em></h2></div><div className="filters">{['ALL','WEDDINGS','CORPORATE','CELEBRATIONS','VENUE'].map(f=><button key={f} className={filter===f?'active':''} onClick={()=>setFilter(f)}>{f}</button>)}</div></div><div className="gallery-grid">{gallery.filter(g=>filter==='ALL'||g[0].toUpperCase()===filter).map((g,i)=><button key={g[1]} className="gallery-item" onClick={()=>setLight(gallery.indexOf(g))}><img src={g[1]} alt="Generic event venue demo" loading="lazy"/><span>{g[0]} · DEMO IMAGE</span></button>)}</div><small className="disclaimer">ALL IMAGERY IS GENERIC DEMO/PLACEHOLDER IMAGERY — NOT ASSOCIATED WITH A REAL BUSINESS.</small></section>
   <section id="packages" className="section pricing"><div className="section-head"><div><p className="kicker">06 / PACKAGES</p><h2>Choose the experience that <em>fits your event.</em></h2></div></div><div className="price-grid">{packages.map((p,i)=><article className={i===1?'featured':''} key={p[0]}>{i===1&&<label>MOST POPULAR DEMO</label>}<span>DEMO PACKAGE</span><h3>{p[0]}</h3><b>{p[1]}</b><small>DEMO PRICING — REPLACE WITH CLIENT'S ACTUAL RATES</small><p>{p[2]}</p><ul>{p.slice(3).map(x=><li key={x}><Check size={14}/>{x}</li>)}</ul><button onClick={()=>go('booking')}>REQUEST A CUSTOM QUOTE <ArrowUpRight size={15}/></button></article>)}</div></section>
   <section className="testimonial"><div className="section-label">07 / SAMPLE TESTIMONIALS</div><div className="quote"><span>“</span><p>{testimonials[slide][1]}</p><strong>— {testimonials[slide][0]}, DEMO CLIENT</strong></div><div className="slider-controls"><button onClick={()=>setSlide((slide+testimonials.length-1)%testimonials.length)}><ChevronLeft/></button><span>{slide+1} / {testimonials.length}</span><button onClick={()=>setSlide((slide+1)%testimonials.length)}><ChevronRight/></button></div></section>
   <section id="booking" className="booking section"><div><p className="kicker">08 / ENQUIRY</p><h2>Let's plan your next <em>grand occasion.</em></h2><p>Tell us what you're planning and a real client website could help visitors find the right space, date and package in just a few steps.</p><div className="conversion-points"><span><Check/> See the venue</span><span><Check/> Compare spaces</span><span><Check/> Request availability</span></div></div>{sent?<div className="success"><div>✓</div><h3>Enquiry received — demo only.</h3><p>Thank you! No real appointment was created and no information was sent anywhere. A client version could connect this form to their preferred booking system.</p><button onClick={()=>setSent(false)}>SEND ANOTHER ENQUIRY</button></div>:<form onSubmit={submit}><div className="form-grid"><label>Full Name<input required placeholder="Your name"/></label><label>Phone Number<input required placeholder="+234 ..."/></label><label>Email<input required type="email" placeholder="you@example.com"/></label><label>Event Type<select required defaultValue=""><option value="">Select event</option><option>Wedding</option><option>Corporate Event</option><option>Birthday & Celebration</option><option>Private Party</option><option>Conference</option><option>Graduation</option></select></label><label>Preferred Date<input required type="date"/></label><label>Number of Guests<input required min="1" type="number" placeholder="e.g. 250"/></label></div><label>Message<textarea rows={4} placeholder="Tell us about your event..."/></label><button className="submit">REQUEST AVAILABILITY <ArrowUpRight size={16}/></button></form>}</section>
   <section id="faqs" className="section faqs"><div className="section-head"><div><p className="kicker">09 / FREQUENTLY ASKED QUESTIONS</p><h2>Questions, <em>answered.</em></h2></div><span className="section-label">DEMO CONTENT</span></div><div className="faq-list">{faqs.map((q,i)=><div className="faq" key={q}><button onClick={()=>setFaq(faq===i?null:i)}><span>0{i+1}</span>{q}<ChevronDown className={faq===i?'open':''}/></button>{faq===i&&<p>This is illustrative demo content. In a real venue website, this answer would be replaced with the client's confirmed policies, capacities and booking information.</p>}</div>)}</div></section>
   <section id="contact" className="contact section"><div className="contact-copy"><p className="kicker">10 / CONTACT</p><h2>Turn a visit into a <em>booking.</em></h2><p>Fictional contact details shown only to demonstrate how a premium venue website could make enquiries easy.</p><button onClick={whatsapp}><MessageCircle size={17}/> CHAT WITH US ON WHATSAPP</button></div><div className="contact-card"><span>DEMO CONTACT INFORMATION</span><p><Phone/> +234 XXX XXX XXXX</p><p><Mail/> hello@grandluxeevents.demo</p><p><MapPin/> Lagos, Nigeria · Location placeholder</p><div className="map"><MapPin size={20}/> MAP PLACEHOLDER · LAGOS</div></div></section>
   <section className="final-cta"><div className="final-bg"/><div><p className="kicker">YOUR BUSINESS COULD LOOK THIS GOOD ONLINE.</p><h2>Your next unforgettable event <em>starts here.</em></h2><p>Explore the spaces, choose your preferred date and let us help you create something extraordinary.</p><div><button onClick={()=>go('booking')}>BOOK A VENUE TOUR <ArrowUpRight size={17}/></button><button className="outline" onClick={whatsapp}><MessageCircle size={17}/> CHAT ON WHATSAPP</button></div></div></section>
  </main>
  <footer><div className="footer-main"><button className="brand" onClick={()=>go('home')}><strong>GRAND LUXE</strong><span>EVENTS</span></button><p>Luxury spaces for life's grandest occasions.<br/><small>Website Concept by Vanessa · Fictional sales demo</small></p><div className="footer-links">{['The Venue','Spaces','Gallery','Packages','FAQs','Contact'].map((x,i)=><button key={x} onClick={()=>go(['venue','spaces','gallery','packages','faqs','contact'][i])}>{x}</button>)}</div></div><div className="footer-bottom"><span>© 2026 Grand Luxe Events · Fictional Demo</span><button onClick={whatsapp}><MessageCircle size={14}/> WhatsApp Demo</button><span>SALES DEMO — NOT AN OFFICIAL BUSINESS WEBSITE</span></div></footer>
  <button className="floating-wa" aria-label="Demo WhatsApp" onClick={whatsapp}><MessageCircle/></button>
  {light!==null&&<div className="lightbox" onClick={()=>setLight(null)}><img src={gallery[light][1]} alt="Expanded generic demo image"/><button onClick={()=>setLight(null)} aria-label="Close"><X/></button></div>}
 </div>
}
export default App;
